### ISSUE TITLE
Transistor Milestone

### ISSUE THREAD

**Issue by driki** [PRX/www.prx.org#277]
**Goal**
Get the Transistor podcast to switch over and start using the PRX provided podcast publishing. 

**Deliverables**
* [ ] http://feeds.prx.org/transistor_stem sourced from the PRX publishing platform, not WP.
* [ ] WSYWIG editor https://github.com/PRX/www.prx.org/issues/275
* [ ] Podcast ingest from RSS https://github.com/PRX/www.prx.org/issues/241
* [ ] Display a podcast button on the series https://github.com/PRX/www.prx.org/issues/269
* [ ] Show me if there is a problem with my audio file https://github.com/PRX/www.prx.org/issues/232
* [ ] Text changes: https://github.com/PRX/www.prx.org/issues/268
* [ ] Ensure that user testing takes place

**Metrics and Targets**

This Milestone will be considered a success when:
* Previously published podcast episodes are available via PRX.
* New Transistor podcast episodes are published via beta.prx.org
* The Transistor podcast feed is migrated from WP

**Comment by debenedictis** [comment]
To be clear, subscribers will retain the feed.press (or previous FeedBurner) address.  When you say "migrate" you mean that feed.press/FeedBurner will get a new URL as the source feed.  Correct?

Also, will the GUIDs be preserved so as to prevent dupes in clients like iTunes?

**Comment by driki** [comment]
@debenedictis Updated the issue to reflect this. You can follow this in more detail here: https://github.com/PRX/www.prx.org/issues/241
